stages:
  - register
  - test
  - release
  - unregister

.imgjob:
  image: docker:stable
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  before_script:
    - mkdir utils
    - apk add --no-cache make bash

.runner:
  image:
    name: hashicorp/terraform:0.14.9
    entrypoint: [""]
  before_script:
    - cd ci/runner
    - terraform init

register:
  extends: .runner
  stage: register
  script:
    - terraform apply -auto-approve

test:
  extends: .imgjob
  stage: test
  only:
    - branches
  except:
    - master
  script:
    - make build
  allow_failure: true

gitlab:
  extends: .imgjob
  stage: release
  only:
    - master
  script:
    - make all

unregister:
  extends: .runner
  stage: unregister
  script:
    - terraform destroy -auto-approve
  when: always
