#!/bin/bash

if [[ ${DOWNLOAD_URL} == *"raspbian"* ]]; then
    echo "Downloading package from Package Cloud - ${RELEASE_VERSION}"
    wget --quiet ${DOWNLOAD_URL} -O /tmp/gitlab.deb
# else
#     echo "Downloading package as artifact - ${DOWNLOAD_URL}"
#     # If we are fetching the package which is available as an artifact, we need
#     # to authenticate to access it. Hence, we pass PRIVATE-TOKEN header.
#     wget --quiet --header "PRIVATE-TOKEN: ${TRIGGER_PRIVATE_TOKEN}" ${DOWNLOAD_URL} -O /tmp/gitlab.deb
fi
