#!/bin/bash

set -eo pipefail

_docker(){
    docker ${@}
}

build() {
    echo -e "\033[1mBuilding image: \033[32m${1}\033[0m"
    _docker build --no-cache --force-rm --compress -t "${1}" -f "${2}" "${3}"
}

# Set the version to install
sed -i -e 's/CE_VERSION/'"$CE_VERSION"'/g' docker/RELEASE

# Build the actual image
build "${IMAGE}:${CE_TAG}" docker/Dockerfile docker/
