#!/bin/bash

set -eo pipefail

_docker(){
    docker ${@}
}

get_hash(){
    echo -e "\033[1mGetting hash: \033[32m${1}\033[0m"
    echo $(_docker images -q --no-trunc "${1}" | awk '{print $0}' | sed 's|sha256:||') > utils/image_hash
}

dk_save(){
    echo -e "\033[1mHash: \033[32m${1}\033[0m"
    echo -e "\033[1mSaving image: \033[32m${IMAGE}:${CE_TAG}\033[0m"
    _docker save "${1}" > "${2}"
}

get_hash "${IMAGE}:${CE_TAG}"
export CURRENT_HASH=$(cat utils/image_hash)
dk_save "${CURRENT_HASH}" utils/gitlab.tar
